package ai.chaski.splashr.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * A photo the user has saved for offline access. The full metadata is stored
 * locally so saved photos remain fully browsable without a network connection.
 * [tags] is persisted as a "|"-joined string (see Mappers.kt).
 */
@Entity(tableName = "saved_photos")
data class SavedPhotoEntity(
    @PrimaryKey val id: String,
    val title: String,
    val description: String,
    val imageUrl: String,
    val photographerId: String,
    val photographerName: String,
    val tags: String,
    val topic: String,
    val width: Int,
    val height: Int,
    val dominantColor: String,
    val savedAt: Long,
)

/** A user-created collection. */
@Entity(tableName = "collections")
data class CollectionEntity(
    @PrimaryKey val id: String,
    val name: String,
    val description: String,
    val createdAt: Long,
)

/** Join row connecting a collection to a photo it contains. */
@Entity(tableName = "collection_photos", primaryKeys = ["collectionId", "photoId"])
data class CollectionPhotoCrossRef(
    val collectionId: String,
    val photoId: String,
    val addedAt: Long,
)

/**
 * A cached AI tag suggestion for a photo. Generating suggestions calls the
 * Claude API, so each photo's result is stored here and reused — every photo is
 * only ever sent to the model once. [tags] is a "|"-joined string.
 */
@Entity(tableName = "ai_suggestions")
data class AiSuggestionEntity(
    @PrimaryKey val photoId: String,
    val tags: String,
    val explanation: String,
    val createdAt: Long,
)

/**
 * A cached AI photo critique. Same caching reason as [AiSuggestionEntity] —
 * critiques are generated by a Claude vision call and only ever produced once
 * per photo.
 */
@Entity(tableName = "ai_critiques")
data class AiCritiqueEntity(
    @PrimaryKey val photoId: String,
    val composition: String,
    val light: String,
    val color: String,
    val takeaway: String,
    val createdAt: Long,
)
